version: "3.8"
services:
    mysql-server:
        image: mysql:8.0.1
        container_name: "final-web-mysql"
        ports:
            - 3306:3306
        restart: always
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: "final-web-admin"
        ports:
            - 8888:80
        restart: always
        environment:
            - PMA_HOST=mysql-server
        depends_on:
            - "mysql-server"